defaults:
  - optim: adam
  - tasks:
      - cola
      - mnli
      - mrpc
      - qnli
      - qqp
      - rte
      - sst2
      - stsb
#      - wnli

metrics_to_average:
  - qqp_f1
  - qnli_accuracy
  - mrpc_f1
  - mnli_accuracy_extra
  - mnli_accuracy
  - stsb_pearson
  - sst2_accuracy
  - rte_accuracy
  - cola_matthews_correlation

optim:
  lr: 4e-5

evaluation_set: validation # always keep this at validation except for the final run

# checkpoint name:
# This can be either "latest", or a reference to a specific checkpoint in a subfolder
checkpoint: latest
# Set this to a non-empty value to specify a particular model file to load.
model_pth:

path: ${impl.path} # Path for caches of datasets and tokenizers
max_seq_length: 128

# Default options:
# These can be overwritten by specific tasks
batch_size: 16
batch_size_ramp: 0

gradient_clipping:
limited_decay_keys: [bias, LayerNorm.bias, LayerNorm.weight] # no weight decay for these layers
scheduler: cosine-decay
optim_mod:
  name: none

epochs: 5

# These options are only used for scheduling:
warmup_steps: 0.1
cooldown_steps: 0
steps: 10_000

testing:
  batch_size: 128

arch_modifications:
  classification_head:
    pooler: zero_index
    include_ff_layer: True
    # head_dim: ${arch.hidden_size}
    nonlin: Tanh
    # classifier_dropout: ${arch.hidden_dropout_prob}
