# This configuration caches the dataset in an LMDB
name: LMDB
draw_cache_directly: False

# writing:
rebuild_existing_database: False
write_frequency: 50_000 # how often to flush during database creation
shuffle_while_writing: False

# reading:
max_readers: 128
readahead: True # this should be beneficial for long sequential reads
meminit: True
max_spare_txns: 128

access: get # cursor or get
